# Docker Compose configuration for Advent Hymnals production deployment
# This is the reference configuration used in production

services:
  advent-hymnals-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: ${ADVENT_HYMNALS_IMAGE:-ghcr.io/adventhymnals/advent-hymnals-web:latest}
    container_name: advent-hymnals-web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - SITE_URL=${SITE_URL:-https://adventhymnals.org}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://adventhymnals.org}
      - GOOGLE_VERIFICATION=${GOOGLE_VERIFICATION}
      - YANDEX_VERIFICATION=${YANDEX_VERIFICATION}
    volumes:
      - hymnal-data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - advent-hymnals-network
    labels:
      - "com.docker.compose.project=advent-hymnals"
      - "com.docker.compose.service=web"

  nginx:
    image: nginx:latest
    container_name: advent-hymnals-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/domains.txt:/etc/nginx/domains.txt
      - ./nginx/entrypoint.sh:/docker-entrypoint.d/30-setup-dns.sh
      - ./logs/nginx:/var/log/nginx
      - certbot-web:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
      - media-files:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=${NGINX_HOST:-adventhymnals.org}
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    depends_on:
      advent-hymnals-web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - advent-hymnals-network
      - web-network
    labels:
      - "com.docker.compose.project=advent-hymnals"
      - "com.docker.compose.service=nginx"

volumes:
  hymnal-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  media-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/sources
  certbot-web:
  certbot-certs:

networks:
  advent-hymnals-network:
    driver: bridge
  web-network:
    external: true