version: '3.8'

services:
  advent-hymnals-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      - SITE_URL=${SITE_URL:-https://adventhymnals.org}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://adventhymnals.org}
      - GOOGLE_VERIFICATION=${GOOGLE_VERIFICATION}
      - YANDEX_VERIFICATION=${YANDEX_VERIFICATION}
    volumes:
      - hymnal-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  hymnal-data:
    driver: local