services:
  media-server:
    image: nginx:alpine
    container_name: adventhymnals-media
    ports:
      - "8082:80"
    volumes:
      - ../../data/sources:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=media.adventhymnals.org
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Log viewer for development
  logs:
    image: amir20/dozzle:latest
    container_name: media-logs
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - development