# Production override for media server
services:
  media-server:
    image: ghcr.io/adventhymnals/media-server:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # In production, media files would be synced or mounted from external storage
      - ./media-files:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL certificates (when configured)
      - ./ssl:/etc/ssl/certs:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=media.adventhymnals.org
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.adventhymnals.org`)"
      - "traefik.http.routers.media.tls=true"
      - "traefik.http.routers.media.tls.certresolver=letsencrypt"