name: Deploy Web App to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'data/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm turbo build --filter=@advent-hymnals/web^...

      - name: Build web app
        run: |
          cd apps/web
          pnpm build
        env:
          NEXT_OUTPUT: export
          NEXT_DISTDIR: out

      - name: Deploy to adventhymnals.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: adventhymnals/adventhymnals.github.io
          deploy_key: ${{ secrets.DEPLOY_SSH_KEY }}
          publish_dir: ./apps/web/out
          publish_branch: master
          cname: adventhymnals.org